"""Add sensors and cameras columns

Revision ID: 51ecf25f4244
Revises: 
Create Date: 2024-12-18 16:24:10.861327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ecf25f4244'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensors', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cameras', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.drop_column('cameras')
        batch_op.drop_column('sensors')

    # ### end Alembic commands ###
