"""Add description column to traffic_light

Revision ID: cf66f936f021
Revises: 94e81a2497ff
Create Date: 2024-12-18 18:44:51.142421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf66f936f021'
down_revision = '94e81a2497ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('density',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('green_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rush_hour_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('sensors',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cameras',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('last_updated')
        batch_op.drop_column('name')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_light', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('cameras',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('sensors',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rush_hour_factor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('green_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('density',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('description')

    # ### end Alembic commands ###
